name: dr_sami
description: "DR Sami Project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  animated_splash_screen: ^1.3.0
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  carousel_slider_plus: ^7.0.1
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  dio: ^5.7.0
  easy_localization: ^3.0.7
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.14
  http: ^1.2.2
  iconly: ^1.0.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  meta: ^1.15.0
  path: ^1.9.0
  path_provider: ^2.1.3
  pinput: ^5.0.0
  shared_preferences: ^2.3.1
  shimmer: ^3.0.0
  skeletonizer: ^2.1.0+1
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_inappwebview: ^6.1.5
  flutter_lints: ^4.0.0
  flutter_paypal_payment: ^1.0.7
  flutter_test:
    sdk: flutter
  quickalert: ^1.1.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/splash_icon12.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/onBoarding/
    - assets/localization/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-VariableFont_wght.ttf
        - asset: assets/fonts/RobotoCondensed-Italic-VariableFont_wght.ttf
          style: italic
  generate: true

flutter_intl:
  enabled: true
